### ISSUE TITLE
Read HSI data 

### ISSUE THREAD

**Issue by aldiak** [swalpa/G2C-Conv3D-HSI#1]
Hello,  I am using a tensorflow-gpu == 1.13.1 and trying to read the .mat file, but it's throwing this error:

Traceback (most recent call last):
  File "run.py", line 225, in <module>
    X, y = loadData(dataset)
  File "run.py", line 50, in loadData
    mat_data = sio.loadmat(data_path + 'PaviaU.mat')
  File "C:\Users\Alou\anaconda3\envs\paper\lib\site-packages\scipy\io\matlab\mio.py", line 226, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "C:\Users\Alou\anaconda3\envs\paper\lib\site-packages\scipy\io\matlab\mio5.py", line 332, in get_variables
    res = self.read_var_array(hdr, process)
  File "C:\Users\Alou\anaconda3\envs\paper\lib\site-packages\scipy\io\matlab\mio5.py", line 292, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 671, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 701, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header
  File "mio5_utils.pyx", line 775, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex
  File "mio5_utils.pyx", line 448, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric
  File "mio5_utils.pyx", line 353, in scipy.io.matlab.mio5_utils.VarReader5.read_element
  File "streams.pyx", line 174, in scipy.io.matlab.streams.ZlibInputStream.read_string
  File "streams.pyx", line 150, in scipy.io.matlab.streams.ZlibInputStream.read_into
  File "streams.pyx", line 137, in scipy.io.matlab.streams.ZlibInputStream._fill_buffer
zlib.error: Error -3 while decompressing data: invalid block type

Please, I need some help. Thanks

**Comment by AnkurDeria** [comment]
Hello, try to update your scipy package and try this again.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by AnkurDeria** [comment]
It would be helpful if you could show me the script.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by aldiak** [comment]
Alright, I will try out. Thanks

**Comment by aldiak** [comment]
Here are the picture of the script and the error message
